---
"x86_64":
  register_size: 8
  register_list: [rax, rbx, rcx, rdx, rsi, rdi, r8, r9, r10, r11, r12, r13, r14, r15]

"i386":
  register_size: 4
  register_list: [eax, ebx, ecx, edx, esi, edi]

"aarch64":
  register_size: 8
  register_list: [x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x24, x25, x26, x27, x28, x29]

"arm":
  register_size: 4
  register_list: [r0, r1, r2, r3, r4, r5, r6, r7, r8, r9, r10, r11, r12]
